module.exports = {
    exportPathMap: function () {
        return {
            "/": { page: "/" },
            "/blog": { page: "/blog" },
            "/kontakt": { page: "/kontakt" },
            "/fotografia-slubna-krakow": { page: "/fotografia-slubna-krakow" },
            "/sesja-zdjeciowa-krakow": { page: "/sesja-zdjeciowa-krakow" },
            "/misja-i-faq": { page: "/misja-i-faq" },
            "/historie-slubne": { page: "/historie-slubne" },
            "/strefa-klienta": { page: "/strefa-klienta" },
            "/polityka-prywatnosci-rodo": { page: "/polityka-prywatnosci-rodo" },
            "/blog/page/1": { page: "/blog", query: { page: "1" } },
            "/blog/page/2": { page: "/blog", query: { page: "2" } },
            "/blog/page/3": { page: "/blog", query: { page: "3" } },
            "/blog/page/4": { page: "/blog", query: { page: "4" } },
            "/blog/page/5": { page: "/blog", query: { page: "5" } },
            "/blog/page/6": { page: "/blog", query: { page: "6" } },
            "/blog/page/7": { page: "/blog", query: { page: "7" } },
            "/blog/page/8": { page: "/blog", query: { page: "8" } },
            "/blog/page/9": { page: "/blog", query: { page: "9" } },
            "/blog/page/10": { page: "/blog", query: { page: "10" } },
            "/blog/page/11": { page: "/blog", query: { page: "11" } },
            "/blog/page/12": { page: "/blog", query: { page: "12" } },
            "/blog/page/13": { page: "/blog", query: { page: "13" } },
            "/blog/page/14": { page: "/blog", query: { page: "14" } },
            "/blog/page/15": { page: "/blog", query: { page: "15" } },
            "/wieczor_panienski_bubble_toast_krakow": { page: "/wieczor_panienski_bubble_toast_krakow" },
            "/sala-weselna-alexia-ochojno-emocje-i-swietna-zabawa": { page: "/sala-weselna-alexia-ochojno-emocje-i-swietna-zabawa" },
            "/wigilia-firmowa-saba-2019": { page: "/wigilia-firmowa-saba-2019" },
            "/wigilia-firmowa-smartrecruiters-2019": { page: "/wigilia-firmowa-smartrecruiters-2019" },
            "/we-are-all-friends-here-letownia-krzczonow-spytkowice": { page: "/we-are-all-friends-here-letownia-krzczonow-spytkowice" },
            "/dworek-fantazja-skomielna-biala-i-slub-w-stylu-glamour": { page: "/dworek-fantazja-skomielna-biala-i-slub-w-stylu-glamour" },
            "/reverse-recruiting-smartow": { page: "/reverse-recruiting-smartow" },
            "/sesja-na-slowacji-tatrzanska-lomnica-szczyrbskie-jezioro": { page: "/sesja-na-slowacji-tatrzanska-lomnica-szczyrbskie-jezioro" },
            "/rebranding-saba": { page: "/rebranding-saba" },
            "/firmowe-spotkanie-smartow": { page: "/firmowe-spotkanie-smartow" },
            "/hotel-zameczek-ksiaz-wielki-i-slubne-iskierki-milosci": { page: "/hotel-zameczek-ksiaz-wielki-i-slubne-iskierki-milosci" },
            "/park-mogilany-i-moc-buziakow-skapanych-w-promieniach-slonca": { page: "/park-mogilany-i-moc-buziakow-skapanych-w-promieniach-slonca" },
            "/sesja-slubna-w-krakowie-miejsca-idealnie-nadajace-sie-na-romantyczne-kadry": { page: "/sesja-slubna-w-krakowie-miejsca-idealnie-nadajace-sie-na-romantyczne-kadry" },
            "/bazylika-bozego-ciala-krakow-fotoreportaz-slubny": { page: "/bazylika-bozego-ciala-krakow-fotoreportaz-slubny" },
            "/miejska-sesja-narzeczenska-piekni-mlodzi-i-zakochani": { page: "/miejska-sesja-narzeczenska-piekni-mlodzi-i-zakochani" },
            "/ciekawe-miejsca-w-krakowie-czyli-pomysl-na-sesje-zdjeciowa": { page: "/ciekawe-miejsca-w-krakowie-czyli-pomysl-na-sesje-zdjeciowa" },
            "/reportaz-slubny-sala-weselna-babie-lato-gdow-cieplutko": { page: "/reportaz-slubny-sala-weselna-babie-lato-gdow-cieplutko" },
            "/fotograf-na-event-firmowy-krakow": { page: "/fotograf-na-event-firmowy-krakow" },
            "/wesele-miedzynarodowe-proszowice-i-polskie-tradycje-weselne": { page: "/wesele-miedzynarodowe-proszowice-i-polskie-tradycje-weselne" },
            "/sala-weselna-karolinka-bystra-podhalanska": { page: "/sala-weselna-karolinka-bystra-podhalanska" },
            "/sala-bankietowa-szafrantu-fotografia-slubna-niepolomice": { page: "/sala-bankietowa-szafrantu-fotografia-slubna-niepolomice" },
            "/hotel-junior-skotnicka-zdjecia-slubne-skawina": { page: "/hotel-junior-skotnicka-zdjecia-slubne-skawina" },
            "/willa-decjusza-krakow-slub-cywilny-sesja-zdjeciowa": { page: "/willa-decjusza-krakow-slub-cywilny-sesja-zdjeciowa" },
            "/jak-zaplanowac-i-zorganizowac-wymarzony-slub-w-zimie": { page: "/jak-zaplanowac-i-zorganizowac-wymarzony-slub-w-zimie" },
            "/hotel-nad-raba-bochnia-zimowy-slub-w-niepolomicach": { page: "/hotel-nad-raba-bochnia-zimowy-slub-w-niepolomicach" },
            "/pomysl-na-sesje-zimowa-w-krakowie-dwor-jana-matejki": { page: "/pomysl-na-sesje-zimowa-w-krakowie-dwor-jana-matejki" },
            "/fotograf-na-wigilie-firmowa-w-krakowie": { page: "/fotograf-na-wigilie-firmowa-w-krakowie" },
            "/zielone-wzgorze-koniusza-tak-w-promieniach-slonca": { page: "/zielone-wzgorze-koniusza-tak-w-promieniach-slonca" },
            "/sesja-slubna-jesienia-palac-goetzow-okocimskich": { page: "/sesja-slubna-jesienia-palac-goetzow-okocimskich" },
            "/dom-weselny-euforia-myslenice-i-sloneczne-love": { page: "/dom-weselny-euforia-myslenice-i-sloneczne-love" },
            "/sala-weselna-helada-fotograf-slubny-oswiecim": { page: "/sala-weselna-helada-fotograf-slubny-oswiecim" },
            "/sala-bankietowa-triana-mogilany-reportaz-slubny-podstolice": { page: "/sala-bankietowa-triana-mogilany-reportaz-slubny-podstolice" },
            "/sesja-slubna-w-pieskowej-skale-i-zamek-korzkiew": { page: "/sesja-slubna-w-pieskowej-skale-i-zamek-korzkiew" },
            "/zamek-moszna-plenerowa-sesja-fotograficzna-w-palacu": { page: "/zamek-moszna-plenerowa-sesja-fotograficzna-w-palacu" },
            "/ogrod-botaniczny-w-krakowie-slubna-sesja-zdjeciowa": { page: "/ogrod-botaniczny-w-krakowie-slubna-sesja-zdjeciowa" },
            "/palac-goetza-brzesko-sluba-sesja-zdjeciowa": { page: "/palac-goetza-brzesko-sluba-sesja-zdjeciowa" },
            "/ciekawe-miejsce-na-plener-slubny-sesja-slubna-w-tatrach": { page: "/ciekawe-miejsce-na-plener-slubny-sesja-slubna-w-tatrach" },
            "/tiffany-wola-filipowska-first-look-na-dachu-wiezowca": { page: "/tiffany-wola-filipowska-first-look-na-dachu-wiezowca" },
            "/hotel-lenart-wieliczka-turkusowy-cadillac-de-ville": { page: "/hotel-lenart-wieliczka-turkusowy-cadillac-de-ville" },
            "/fotograf-slubny-krzeszowice-cztery-pory-roku-alwernia": { page: "/fotograf-slubny-krzeszowice-cztery-pory-roku-alwernia" },
            "/sesja-narzeczenska-w-krakowie-i-okolicach-wygielzow": { page: "/sesja-narzeczenska-w-krakowie-i-okolicach-wygielzow" },
            "/sala-weselna-willa-orchidea-waksmund-slub-w-pieninach": { page: "/sala-weselna-willa-orchidea-waksmund-slub-w-pieninach" },
            "/sesja-slubna-zielonym-szlakiem-na-popradzki-staw": { page: "/sesja-slubna-zielonym-szlakiem-na-popradzki-staw" },
            "/fotograf-slubny-sucha-beskidzka-magnolia-budzow": { page: "/fotograf-slubny-sucha-beskidzka-magnolia-budzow" },
            "/fotograf-slubny-kalwaria-zebrzydowska-arkadia-wadowice": { page: "/fotograf-slubny-kalwaria-zebrzydowska-arkadia-wadowice" },
            "/impreza-rodzinna-stadnina-koni-botoja-korzkiew": { page: "/impreza-rodzinna-stadnina-koni-botoja-korzkiew" },
            "/reportaz-slubny-hotel-junior-krakow-balonowy-szal": { page: "/reportaz-slubny-hotel-junior-krakow-balonowy-szal" },
            "/slub-w-lanckoronie-restauracja-old-joker-jaroszowice": { page: "/slub-w-lanckoronie-restauracja-old-joker-jaroszowice" },
            "/sala-weselna-folwark-zalesie-reportaz-slubny-wieliczka": { page: "/sala-weselna-folwark-zalesie-reportaz-slubny-wieliczka" },
            "/przystan-w-kabanosie-spytkowice-zdjecia-slubne-jordanow": { page: "/przystan-w-kabanosie-spytkowice-zdjecia-slubne-jordanow" },
            "/plener-slubny-slowacja-lomnicki-staw-szczyrbskie-pleso": { page: "/plener-slubny-slowacja-lomnicki-staw-szczyrbskie-pleso" },
            "/cztery-pory-roku-alwernia-reportaz-slubny-chelmek": { page: "/cztery-pory-roku-alwernia-reportaz-slubny-chelmek" },
            "/sala-weselna-villa-marina-dabrowa-gornicza-slub-nad-jeziorem": { page: "/sala-weselna-villa-marina-dabrowa-gornicza-slub-nad-jeziorem" },
            "/hotel-margerita-magiczny-wystroj-sali-weselnej-w-krakowie": { page: "/hotel-margerita-magiczny-wystroj-sali-weselnej-w-krakowie" },
            "/sesja-slubna-krakow-rynek-glowny-wawel-kazimierz": { page: "/sesja-slubna-krakow-rynek-glowny-wawel-kazimierz" },
            "/dom-weselny-aleksandra-zdjecia-slubne-mszana-dolna": { page: "/dom-weselny-aleksandra-zdjecia-slubne-mszana-dolna" },
            "/dom-weselny-w-jablonce-zdjecia-slubne-przystan-w-kabanosie": { page: "/dom-weselny-w-jablonce-zdjecia-slubne-przystan-w-kabanosie" },
            "/zimowy-slub-w-kosciele-na-szklanych-domach-nowa-huta-krakow": { page: "/zimowy-slub-w-kosciele-na-szklanych-domach-nowa-huta-krakow" },
            "/karczma-pod-kogutkiem-krzywaczka-reportaz-slubny-makow-podhalanski": { page: "/karczma-pod-kogutkiem-krzywaczka-reportaz-slubny-makow-podhalanski" },
            "/sesja-zdjeciowa-dwor-tomaszowice-opera-kazimierz": { page: "/sesja-zdjeciowa-dwor-tomaszowice-opera-kazimierz" },
            "/sesja-slubna-strbskie-pleso-i-popradzki-staw-slowacja": { page: "/sesja-slubna-strbskie-pleso-i-popradzki-staw-slowacja" },
            "/wesele-w-goralskim-klimacie-przystan-kabanos-spytkowice": { page: "/wesele-w-goralskim-klimacie-przystan-kabanos-spytkowice" },
            "/zdjecia-slubne-restauracja-stek-skawina": { page: "/zdjecia-slubne-restauracja-stek-skawina" },
            "/opactwo-cystersow-w-mogile-sesja-zdjeciowa-kasprowy": { page: "/opactwo-cystersow-w-mogile-sesja-zdjeciowa-kasprowy" },
            "/sesja-slubna-w-plenerze-park-krajobrazowy-w-ojcowie-i-okolice": { page: "/sesja-slubna-w-plenerze-park-krajobrazowy-w-ojcowie-i-okolice" },
            "/dwor-szlachecki-sieciechowice-reportaz-slubny-miechow": { page: "/dwor-szlachecki-sieciechowice-reportaz-slubny-miechow" },
            "/sesja-zdjeciowa-zakrzowek-skalki-twardowskiego-krakow": { page: "/sesja-zdjeciowa-zakrzowek-skalki-twardowskiego-krakow" },
            "/dom-weselny-marion-wesele-tarnow-i-zdjecia-slubne": { page: "/dom-weselny-marion-wesele-tarnow-i-zdjecia-slubne" },
            "/sala-weselna-nedan-pcim-reportaz-slubny": { page: "/sala-weselna-nedan-pcim-reportaz-slubny" },
            "/fotograf-na-wesele-jordanow-straznica-pcim": { page: "/fotograf-na-wesele-jordanow-straznica-pcim" },
            "/sesja-zdjeciowa-park-w-mogilanach-zakrzowek-i-kazimierz": { page: "/sesja-zdjeciowa-park-w-mogilanach-zakrzowek-i-kazimierz" },
            "/slub-cywilny-i-wesele-w-plenerze-witkowa-chata-krakow": { page: "/slub-cywilny-i-wesele-w-plenerze-witkowa-chata-krakow" },
            "/plener-narzeczenski-krakow-i-okolice": { page: "/plener-narzeczenski-krakow-i-okolice" },
            "/wesele-na-polu-golfowym-w-paczoltowicach": { page: "/wesele-na-polu-golfowym-w-paczoltowicach" },
            "/wakacyjny-test-obiektywu-sigma-50-1-4-art": { page: "/wakacyjny-test-obiektywu-sigma-50-1-4-art" },
            "/hotel-qubus-krakow-sesja-zdjeciowa": { page: "/hotel-qubus-krakow-sesja-zdjeciowa" },
            "/hotel-tadeusz-uszew-i-goralska-sala-weselna": { page: "/hotel-tadeusz-uszew-i-goralska-sala-weselna" },
            "/sesja-narzeczenska-krakow": { page: "/sesja-narzeczenska-krakow" },
            "/lawendowe-pole-pod-krakowem-sesja-slubna-w-ostrowie": { page: "/lawendowe-pole-pod-krakowem-sesja-slubna-w-ostrowie" },
            "/dom-weselny-pod-kasztanami-igolomia": { page: "/dom-weselny-pod-kasztanami-igolomia" },
            "/sala-bankietowa-i-weselna-krzczonow-mka-morze-gwiazd": { page: "/sala-bankietowa-i-weselna-krzczonow-mka-morze-gwiazd" },
            "/sesja-zdjeciowa-kopiec-kraka-przegorzaly-kryspinow": { page: "/sesja-zdjeciowa-kopiec-kraka-przegorzaly-kryspinow" },
            "/dekoracja-sali-weselnej-w-stylu-rustykalnym-osp-zawada": { page: "/dekoracja-sali-weselnej-w-stylu-rustykalnym-osp-zawada" },
            "/dom-weselny-babie-lato-gdow-reportaz-slubny": { page: "/dom-weselny-babie-lato-gdow-reportaz-slubny" },
            "/wesele-tarnow-dwor-bistuszowa-i-staropolski-klimat-slubny": { page: "/wesele-tarnow-dwor-bistuszowa-i-staropolski-klimat-slubny" },
            "/sesje-plenerowe-slubne-w-sercu-krakowa": { page: "/sesje-plenerowe-slubne-w-sercu-krakowa" },
            "/zdjecia-chrztu-swietego-i-slubu-krakow": { page: "/zdjecia-chrztu-swietego-i-slubu-krakow" },
            "/zdjecia-slubne-restauracja-stek-myslenice": { page: "/zdjecia-slubne-restauracja-stek-myslenice" },
            "/kinga-i-sergiusz-reportaz-slubny-dom-weseleny-akacjowy-dwor-krakow": { page: "/kinga-i-sergiusz-reportaz-slubny-dom-weseleny-akacjowy-dwor-krakow" },
            "/kasia-i-pawel-zimowa-sesja-slubna-w-gorach": { page: "/kasia-i-pawel-zimowa-sesja-slubna-w-gorach" },
            "/paulina-i-marcin-reportaz-slubny-hotel-europejski-krakow": { page: "/paulina-i-marcin-reportaz-slubny-hotel-europejski-krakow" },
            "/alina-i-janusz-zdjecia-slubne-jordanow-dworek-fantazja": { page: "/alina-i-janusz-zdjecia-slubne-jordanow-dworek-fantazja" },
            "/natalia-i-marcin-sesja-slubna-pieskowa-skala-i-ojcow": { page: "/natalia-i-marcin-sesja-slubna-pieskowa-skala-i-ojcow" },
            "/sabina-i-wiesiek-zdjecia-slubne-dworek-fantazja-skomielna-biala": { page: "/sabina-i-wiesiek-zdjecia-slubne-dworek-fantazja-skomielna-biala" },
            "/kinga-i-sebastian-sesja-slubna-park-zamkowy-zywiec": { page: "/kinga-i-sebastian-sesja-slubna-park-zamkowy-zywiec" },
            "/kinga-i-sebastian-reportaz-slubny-wadowice-chocznia-i-radocza": { page: "/kinga-i-sebastian-reportaz-slubny-wadowice-chocznia-i-radocza" },
            "/natalia-marcin-i-maja-reportaz-slubny-gosciniec-branicki": { page: "/natalia-marcin-i-maja-reportaz-slubny-gosciniec-branicki" },
            "/julita-i-pawel-reportaz-slubny-kosciol-na-skalce-krakow": { page: "/julita-i-pawel-reportaz-slubny-kosciol-na-skalce-krakow" },
            "/marlena-i-dawid-zdjecia-slubne-z-goralskiego-slubu-w-osadzie-kamienica": { page: "/marlena-i-dawid-zdjecia-slubne-z-goralskiego-slubu-w-osadzie-kamienica" },
            "/kasia-i-grzegorz-sesja-slubna-wawel-przegorzaly-i-kryspinow": { page: "/kasia-i-grzegorz-sesja-slubna-wawel-przegorzaly-i-kryspinow" },
            "/kasia-i-grzesiek-zdjecia-slubne-w-kosciele-pw-sw-klemensa-w-trzemesni": { page: "/kasia-i-grzesiek-zdjecia-slubne-w-kosciele-pw-sw-klemensa-w-trzemesni" },
            "/monika-i-rafal-zdjecia-slubne-krakow-restauracja-chocholowy-dwor": { page: "/monika-i-rafal-zdjecia-slubne-krakow-restauracja-chocholowy-dwor" },
            "/angelika-i-dawid-plener-slubny-zamek-pieskowa-skala": { page: "/angelika-i-dawid-plener-slubny-zamek-pieskowa-skala" },
            "/angelika-i-dawid-reportaz-slubny-krakow-restauracja-viva-michalowice": { page: "/angelika-i-dawid-reportaz-slubny-krakow-restauracja-viva-michalowice" },
            "/paulina-i-darek-reportaz-slubny-krakow-skansen-smakow-w-kryspinowie": { page: "/paulina-i-darek-reportaz-slubny-krakow-skansen-smakow-w-kryspinowie" },
            "/michas-i-martusia-wakacje-wroclaw-i-kudowa-zdroj": { page: "/michas-i-martusia-wakacje-wroclaw-i-kudowa-zdroj" },
            "/gosia-i-tomek-sesja-slubna-dolina-bolechowicka-i-kryspinow": { page: "/gosia-i-tomek-sesja-slubna-dolina-bolechowicka-i-kryspinow" },
            "/gosia-i-tomek-reportaz-slubny-bolechowice-dom-weselny-u-niedzwiedzia": { page: "/gosia-i-tomek-reportaz-slubny-bolechowice-dom-weselny-u-niedzwiedzia" },
            "/beata-i-marcin-reportaz-slubny-mszana-dolna-hotel-gorski-raj": { page: "/beata-i-marcin-reportaz-slubny-mszana-dolna-hotel-gorski-raj" },
            "/natalia-i-darek-sesja-slubna-krakow-i-pieskowa-skala": { page: "/natalia-i-darek-sesja-slubna-krakow-i-pieskowa-skala" },
            "/ania-i-maciek-wesele-w-domu-weselnym-szlachecki-dwor-sieciechowice": { page: "/ania-i-maciek-wesele-w-domu-weselnym-szlachecki-dwor-sieciechowice" },
            "/sylwia-i-bartek-sesja-poslubna-krakow": { page: "/sylwia-i-bartek-sesja-poslubna-krakow" },
            "/sylwia-i-bartek-zdjecia-slubne-w-jordanowie": { page: "/sylwia-i-bartek-zdjecia-slubne-w-jordanowie" },
            "/sesja-poslubna-magdy-i-mateusza-litwinska-grapa-w-czarnej-gorze": { page: "/sesja-poslubna-magdy-i-mateusza-litwinska-grapa-w-czarnej-gorze" },
            "/magda-i-mateusz-zdjecia-slubne-w-domu-weselnym-rancho-lot-w-nowym-targu": { page: "/magda-i-mateusz-zdjecia-slubne-w-domu-weselnym-rancho-lot-w-nowym-targu" },
            "/ania-i-krzysiek-zdjecia-slubne-w-domu-weselnym-u-niedzwiedzia": { page: "/ania-i-krzysiek-zdjecia-slubne-w-domu-weselnym-u-niedzwiedzia" },
            "/kasia-i-dariusz-zdjecia-slubne-w-domu-weselnym-willa-podlesie": { page: "/kasia-i-dariusz-zdjecia-slubne-w-domu-weselnym-willa-podlesie" },
            "/natalia-i-dariusz-zdjecia-slubne-w-domu-weselnym-gosciniec-branicki-2": { page: "/natalia-i-dariusz-zdjecia-slubne-w-domu-weselnym-gosciniec-branicki-2" },
            "/gabrysia-i-kuba-zdjecia-slubne-w-folwark-stara-winiarnia": { page: "/gabrysia-i-kuba-zdjecia-slubne-w-folwark-stara-winiarnia" },
            "/kasia-i-pawel-zdjecia-slubne-w-hotelu-ferro-express-krakow": { page: "/kasia-i-pawel-zdjecia-slubne-w-hotelu-ferro-express-krakow" },
            "/krakowska-sesja-poslubna-renaty-i-jacka": { page: "/krakowska-sesja-poslubna-renaty-i-jacka" },
            "/renata-i-jacek-zdjecia-slubne-palac-smilowice": { page: "/renata-i-jacek-zdjecia-slubne-palac-smilowice" },
            "/aga-i-michal-sesja-poslubna-wawel-rynek-krakow": { page: "/aga-i-michal-sesja-poslubna-wawel-rynek-krakow" },
            "/aga-michal-i-zuzia-zdjecia-slubne-zajazd-polesie-przybyslawice": { page: "/aga-michal-i-zuzia-zdjecia-slubne-zajazd-polesie-przybyslawice" },
            "/zuza-i-jarek-sesja-poslubna-kopiec-kosciuszki-i-wawel": { page: "/zuza-i-jarek-sesja-poslubna-kopiec-kosciuszki-i-wawel" },
            "/monika-i-marek-sesja-poslubna-rabkoland-rabka-zdroj": { page: "/monika-i-marek-sesja-poslubna-rabkoland-rabka-zdroj" },
            "/zuza-i-jarek-zdjecia-slubne-modrzewiowe-wzgorze-zakliczyn": { page: "/zuza-i-jarek-zdjecia-slubne-modrzewiowe-wzgorze-zakliczyn" },
            "/paulina-i-bartek-sesja-poslubna-kasprowy-wierch-i-nosal-zakopane": { page: "/paulina-i-bartek-sesja-poslubna-kasprowy-wierch-i-nosal-zakopane" },
            "/pati-i-michal-sesja-poslubna-zamek-w-korzkwi-i-kladka-bernatka": { page: "/pati-i-michal-sesja-poslubna-zamek-w-korzkwi-i-kladka-bernatka" },
            "/paulina-i-bartek-zdjecia-slubne-zajazd-furmanski-zakopane": { page: "/paulina-i-bartek-zdjecia-slubne-zajazd-furmanski-zakopane" },
            "/pati-i-michal-zdjecia-slubne-w-hotelu-turowka-wieliczka": { page: "/pati-i-michal-zdjecia-slubne-w-hotelu-turowka-wieliczka" },
            "/agata-i-mateusz-dwor-w-tomaszowicach-zamek-w-korzkwi-i-ojcow": { page: "/agata-i-mateusz-dwor-w-tomaszowicach-zamek-w-korzkwi-i-ojcow" },
            "/agata-i-mateusz-zdjecia-slubne-w-restauracji-ptaszyl-na-kazimierzu": { page: "/agata-i-mateusz-zdjecia-slubne-w-restauracji-ptaszyl-na-kazimierzu" },
            "/patrycja-i-michal-sesja-narzeczenska-pieskowa-skala": { page: "/patrycja-i-michal-sesja-narzeczenska-pieskowa-skala" },
            "/iga-i-marcin-sesja-poslubna-kazimierz-krakow": { page: "/iga-i-marcin-sesja-poslubna-kazimierz-krakow" },
            "/magda-i-lucjan-zdjecia-slubne-w-restauracji-magnolia-budzow": { page: "/magda-i-lucjan-zdjecia-slubne-w-restauracji-magnolia-budzow" },
            "/sesja-poslubna-wiolety-i-marcina-mogilany-i-kazimierz": { page: "/sesja-poslubna-wiolety-i-marcina-mogilany-i-kazimierz" },
            "/iga-i-marcin-zdjecia-slubne-kosciol-skomielna-czarna": { page: "/iga-i-marcin-zdjecia-slubne-kosciol-skomielna-czarna" },
            "/wioleta-i-marcin-zdjecia-slubne-w-restauracji-victoria-rabka-zdroj": { page: "/wioleta-i-marcin-zdjecia-slubne-w-restauracji-victoria-rabka-zdroj" },
            "/ulubione-wakacyjne-kadry": { page: "/ulubione-wakacyjne-kadry" }
        };
    }
};
